#!/usr/bin/env python3
"""Create / update pages/colecciones/<slug>/index.html for every active garment in public/db/prendas.json.

    python tools/generar-paginas-prenda.py

The page is rendered by renderGarment() in js/catalogo.jsx, which reads the JSON at load time, so price, colour or
description changes need no regeneration. Re-run only after adding a garment or changing slug, name, short or
price_from_mxn (copied into <head> and schema.org for search engines).
Garment folders whose slug is no longer in the database are listed, not deleted.
"""
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = 'https://limonada.com.mx'
OUT = ROOT / 'pages' / 'colecciones'

TEMPLATE = """<!DOCTYPE html>
<html lang="es-MX">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <meta name="description" content="{description}">
    <link rel="canonical" href="{url}">
    <meta property="og:title" content="{title}">
    <meta property="og:description" content="{description}">
    <meta property="og:url" content="{url}">
    <meta property="og:type" content="product">
    <link rel="icon" href="/img/favicon.svg" type="image/svg+xml">
    <meta name="theme-color" content="#14213d">
    <script type="application/ld+json">{jsonld}</script>

    <script src="https://cdn.tailwindcss.com"></script>
    <script src="/js/tailwind.config.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&family=DM+Serif+Display&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/css/site.css">

    <script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/react/18.2.0/umd/react.production.min.js"></script>
    <script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.2.0/umd/react-dom.production.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/7.23.5/babel.min.js"></script>
</head>
<body>

    <div id="root"></div>

    <script type="text/babel" src="/js/layout.jsx"></script>
    <script type="text/babel" src="/js/catalogo.jsx"></script>
    <script type="text/babel">
        // Generated by tools/generar-paginas-prenda.py. The garment is found from this page's URL.
        renderGarment();
    </script>
</body>
</html>
"""

LINES = {'dama': 'Dama', 'caballero': 'Caballero'}


def main():
    garments = json.loads((ROOT / 'public' / 'db' / 'prendas.json').read_text(encoding='utf-8'))['garments']
    active = [g for g in garments if g.get('active', True)]

    for g in active:
        url = f"{SITE}/pages/colecciones/{g['slug']}/"
        title = f"{g['name']} {LINES.get(g['line_id'], '')} · Uniformes ejecutivos Limonada"
        jsonld = {
            '@context': 'https://schema.org', '@type': 'Product',
            'name': f"{g['name']} {LINES.get(g['line_id'], '')}".strip(), 'sku': g['sku'], 'description': g['description'],
            'brand': {'@type': 'Brand', 'name': 'Limonada'},
        }
        if g.get('price_from_mxn'):
            jsonld['offers'] = {'@type': 'AggregateOffer', 'url': url, 'priceCurrency': 'MXN', 'lowPrice': g['price_from_mxn'],
                                'eligibleQuantity': {'@type': 'QuantitativeValue', 'minValue': g['min_qty']}}
        out = OUT / g['slug'] / 'index.html'
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(TEMPLATE.format(
            title=html.escape(title), description=html.escape(f"{g['short']} {g['description']}"), url=url,
            jsonld=json.dumps(jsonld, ensure_ascii=False).replace('</', '<\\/'),
        ), encoding='utf-8', newline='\n')
        print(f"ok   pages/colecciones/{g['slug']}/")

    slugs = {g['slug'] for g in active}
    for d in OUT.iterdir():
        if d.is_dir() and d.name not in slugs:
            print(f"OJO  pages/colecciones/{d.name}/ ya no está en la base de datos: bórrala y añade la ruta a MOVED en 404.html")


if __name__ == '__main__':
    main()
